spring.application.name=tienda_app
spring.datasource.url=jdbc:mysql://localhost:3306/tienda_app?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=BAD115
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

